package com.example.beans;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

import java.util.UUID;

public abstract class DynamoDBEntry<T> {


    private String id;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public DynamoDBEntry() {
    }

    public abstract String generateId();

}
