package com.example.beans;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

import java.awt.font.TransformAttribute;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.Date;
import java.util.UUID;

@DynamoDBDocument
public class Transaction extends DynamoDBEntry<Transaction>  implements Serializable {

    private String id;

    private float amount;

    private String receiver;

    private String sendDate;

    private String message;

    public Transaction() {
    }


    public Transaction(float amount, String receiver, Date sendDate, String message) {
        this.id = UUID.randomUUID().toString();
        this.amount = amount;
        this.receiver = receiver;
        this.sendDate = new SimpleDateFormat("yyyyMMdd_HHmmss").format(Calendar.getInstance().getTime());
        this.message = message;
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "amount")
    public float getAmount() {
        return amount;
    }

    @DynamoDBAttribute(attributeName = "receiver")
    public String getReceiver() {
        return receiver;
    }

    @DynamoDBAttribute(attributeName = "sendDate")
    public String getSendDate() {
        return sendDate;
    }

    @DynamoDBAttribute(attributeName = "message")
    public String getMessage() {
        return message;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Override
    public String generateId() {
        String id = UUID.randomUUID().toString();
        this.setId(id);
        return id;
    }

    public void setAmount(float amount) {
        this.amount = amount;
    }

    public void setSendDate(String sendDate) {
        this.sendDate = sendDate;
    }

    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    public String generateSendDate() {
        String date = new SimpleDateFormat("yyyyMMdd_HHmmss").format(Calendar.getInstance().getTime());
        this.setSendDate(date);
        return date;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}
